name: Deploy Node.js App to Server

on:
  push:
    branches:
      - main  # This triggers the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no anandu@65.108.49.72 "
          cd /home/anandu/test-site/public/github-cicd &&
          git pull origin main &&
          npm install &&
          pm2 restart server.js
        "
